# -*- coding: utf-8 -*-
"""ULTIMATE SAFE CODE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hzht3DI7J8WWUr0BysMY6KQnrDIL4PpW
"""

!pip install yfinance --upgrade --no-cache-dir

!pip install -q fredapi

import yfinance as yf
import pandas as pd
import numpy as np
import time
import scipy.stats as stats
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display
import os
import zipfile
from fredapi import Fred
import requests
import base64
from IPython.display import display, HTML

# === API KEYS ===
FRED_API_KEY = 'c7ced69c1edf727fcf857d31d4043121'
FINNHUB_API_KEY = 'd9k2qc9r01qkjjrrpuggd9k2qc9r01qkjjrrpuh0'

# === GLOBAL TRANSLATION MATRIX/SECTOR MULTIPLES ===

geopolitical_risk_matrix = {
    'United States': 0.00, 'Canada': 0.00, 'United Kingdom': 0.005,
    'China': 0.015, 'India': 0.025, 'Brazil': 0.035, 'Russia': 0.20
}

def get_size_premium(market_cap_billions):
    if pd.isna(market_cap_billions): return 0.02
    if market_cap_billions >= 50.0: return 0.00
    if market_cap_billions >= 10.0: return 0.005
    if market_cap_billions >= 2.0: return 0.012
    if market_cap_billions >= 0.3: return 0.025
    return 0.045

sector_adjustment_matrix = {
    'Technology': {'smooth_fcf': True, 'wacc_modifier': 0.00},
    'Consumer Cyclical': {'smooth_fcf': True, 'wacc_modifier': 0.00},
    'Communication Services': {'smooth_fcf': True, 'wacc_modifier': 0.00},
    'Utilities': {'smooth_fcf': False, 'wacc_modifier': -0.01},
    'Real Estate': {'smooth_fcf': False, 'wacc_modifier': 0.00}
}

sector_exit_multiples = {
    'Technology': 18.5, 'Consumer Cyclical': 12.0, 'Consumer Defensive': 14.0,
    'Communication Services': 15.0, 'Healthcare': 14.5, 'Financial Services': 10.0,
    'Energy': 7.5, 'Industrials': 12.5, 'Real Estate': 16.0, 'Utilities': 10.0, 'Basic Materials': 8.5
}

sector_sales_multiples = {
    'Technology': 6.0, 'Consumer Cyclical': 1.5, 'Consumer Defensive': 1.0,
    'Communication Services': 4.0, 'Healthcare': 4.5, 'Financial Services': 2.5,
    'Energy': 1.2, 'Industrials': 1.8, 'Real Estate': 5.0, 'Utilities': 2.0, 'Basic Materials': 1.5
}


macro_sector_multipliers = {
    'Recovery': {'Technology': 1.15, 'Consumer Cyclical': 1.15, 'Industrials': 1.10, 'Utilities': 0.85, 'Consumer Defensive': 0.90},
    'Overheat': {'Energy': 1.25, 'Basic Materials': 1.20, 'Technology': 0.95, 'Utilities': 0.90},
    'Stagflation': {'Utilities': 1.20, 'Consumer Defensive': 1.15, 'Healthcare': 1.15, 'Consumer Cyclical': 0.75, 'Technology': 0.85},
    'Reflation': {'Real Estate': 1.15, 'Financial Services': 1.15, 'Consumer Cyclical': 1.10, 'Energy': 0.85},
    'Neutral': {}
}

# ==============================================================================
# === SECTION 0: MACROECONOMIC HARVESTER & REGIME NOWCASTING ===
# MATH, LOGIC & DEFENSE STRATEGY:
# This module operates as the engine's "Nowcasting" matrix. It does not predict the
# future; it strictly reads Federal Reserve API data to map the current economic reality,
# mirroring Ray Dalio's All-Weather quadrant (mapping Growth vs. Inflation).
#
# 1. INFLATION (Core PCE YoY): We explicitly use Core PCE rather than standard CPI.
#    Defense: Core PCE strips out highly volatile, geopolitically driven food and
#    energy shocks to isolate "sticky" underlying inflation. Crucially, it is the
#    exact target metric used by the Federal Reserve to dictate interest rate policy.
#
# 2. ECONOMIC GROWTH (TCU - Total Capacity Utilization): Measures the percentage of
#    US industrial infrastructure currently active.
#    Defense: A rising TCU is a leading indicator for corporate CapEx (Capital Expenditure)
#    expansion. It proves factories are ramping up to meet actual consumer demand.
#
# 3. RECESSION SIGNAL (T10Y2Y Yield Curve): 10-Year minus 2-Year Treasury yields.
#    Defense: An inverted curve (< 0) proves institutional capital is terrified of
#    near-term risk, fleeing into 10-year safe-haven bonds (which drives the long-term
#    yield down) and choking off short-term liquidity.
#
# 4. CRASH MODE DETECTION (High-Yield Credit Spread Z-Score):
#    Math: Z = (Current Spread - 90-Day Mean) / 90-Day Standard Deviation.
#    Defense: The bond market is traditionally smarter and faster than the stock market.
#    If the premium investors demand to hold risky corporate "Junk" bonds suddenly spikes
#    >2.0 standard deviations above the norm, it mathematically signals an abnormal
#    institutional panic. The engine detects this and automatically defaults to defensive posture.
# ==============================================================================


def determine_macro_regime(api_key):
    """
    Pulls live economic data from the Federal Reserve to determine the current macroeconomic phase.
    Outputs: Regime String, Yield Curve Inversion Boolean
    """
    if not api_key or api_key == 'YOUR_FRED_API_KEY_HERE':
        print("⚠️ FRED API Key missing. Defaulting to 'Neutral' Macro Regime.")
        return 'Neutral', False

    try:
        fred = Fred(api_key=api_key)

        # 1. Inflation Momentum (Core PCE YoY Rate of Change)
        pce = fred.get_series('PCEPILFE').dropna()
        pce_yoy = pce.pct_change(periods=12) * 100
        inflation_rising = pce_yoy.iloc[-1] > pce_yoy.iloc[-4]

        # 2. Economic Growth Momentum (Capacity Utilization)
        tcu = fred.get_series('TCU').dropna()
        growth_rising = tcu.iloc[-1] > tcu.iloc[-4]

        # 3. Bond Market Fear (10Y-2Y Treasury Spread)
        yield_curve = fred.get_series('T10Y2Y').dropna()
        is_inverted = yield_curve.iloc[-1] < 0


        if growth_rising and not inflation_rising:
            regime = "Recovery"
        elif growth_rising and inflation_rising:
            regime = "Overheat"
        elif not growth_rising and inflation_rising:
            regime = "Stagflation"
        else:
            regime = "Reflation"

        print(f"\n MACRO REGIME DETECTED: {regime.upper()}")
        print(f"   ↳ Inflation Trend (Core PCE): {'Rising 📈' if inflation_rising else 'Falling 📉'}")
        print(f"   ↳ Growth Trend (Capacity): {'Rising 📈' if growth_rising else 'Falling 📉'}")
        print(f"   ↳ Yield Curve (10Y-2Y): {'Inverted ⚠️' if is_inverted else 'Normal ✅'}\n")

        return regime, is_inverted

    except Exception as e:
        print(f"\n FRED API Access Error: {e}. Defaulting to Neutral.")
        return "Neutral", False

def detect_market_crash(api_key):
    """
    Pulls High-Yield Credit Spreads to detect institutional panic.
    Calculates a 90-day rolling Z-Score. If Z-Score > 2.0, triggers Crash Mode.
    """
    if not api_key or api_key == 'YOUR_FRED_API_KEY_HERE':
        return False

    try:
        fred = Fred(api_key=api_key)
        spreads = fred.get_series('BAMLC0A0CM').dropna()

        if len(spreads) < 90:
            return False

        recent_spreads = spreads.tail(90)
        current_spread = recent_spreads.iloc[-1]
        mean_spread = recent_spreads.mean()
        std_spread = recent_spreads.std()

        z_score = (current_spread - mean_spread) / std_spread if std_spread > 0 else 0

        is_crash = z_score > 2.0

        if is_crash:
            print(f" NOWCAST ALERT: Credit Spreads Spiking (Z-Score: {z_score:.2f}). CRASH MODE ACTIVATED.")
        else:
            print(f" NOWCAST STATUS: Credit Markets Stable (Z-Score: {z_score:.2f}).")

        return is_crash

    except Exception as e:
        print(f"⚠️ Nowcast API Error: {e}")
        return False

def fetch_nlp_sentiment(ticker, api_key):
    """
    Pulls free company news headlines using Finnhub and calculates
    a basic keyword-based sentiment score from -1.0 to 1.0.
    """
    if not api_key or api_key == 'YOUR_FINNHUB_API_KEY_HERE':
        return 0.0

    try:
        # Use the free Company News endpoint instead of News Sentiment
        from datetime import datetime, timedelta
        to_date = datetime.today().strftime('%Y-%m-%d')
        from_date = (datetime.today() - timedelta(days=7)).strftime('%Y-%m-%d')

        url = f"https://finnhub.io/api/v1/company-news?symbol={ticker}&from={from_date}&to={to_date}&token={api_key}"
        response = requests.get(url, timeout=5)
        articles = response.json()

        if not isinstance(articles, list) or len(articles) == 0:
            return 0.0

        bullish_words = ['surge', 'jump', 'beat', 'growth', 'record', 'upgrade', 'profit', 'rally', 'high', 'buy']
        bearish_words = ['plunge', 'drop', 'miss', 'fall', 'loss', 'downgrade', 'lawsuit', 'investigation', 'slash', 'low']

        score = 0
        count = 0

        for article in articles[:15]:
            text = (article.get('headline', '') + " " + article.get('summary', '')).lower()
            if not text.strip():
                continue
            count += 1
            for word in bullish_words:
                if word in text:
                    score += 1
            for word in bearish_words:
                if word in text:
                    score -= 1

        if count == 0:
            return 0.0


        normalized = max(min(score / (count * 1.5), 1.0), -1.0)
        return round(normalized, 2)

    except Exception as e:
        return 0.0
# ==============================================================================
# === SECTION 1: SECTOR-ADAPTIVE GRADING SCALES & FUNDAMENTAL FILTERING ===
# MATH, LOGIC & DEFENSE STRATEGY:
# This module prevents the "Apples to Oranges" comparison trap. It normalizes
# absolute financial ratios into a uniform 1-10 scoring system, dynamically
# shifting the goalposts based on a company's sector and business model.
#
# 1. MARGIN & TURNOVER DYNAMICS (DuPont Analysis):
#    Defense: The engine automatically lowers margin requirements for Consumer
#    Defensive/Cyclical stocks. A 2% margin grocery store scores a perfect 10
#    if its Asset Turnover is elite. You are screening for total cash velocity
#    (Return on Equity), not just static profit margins.
#
# 2. CAPITAL STRUCTURE NEUTRALIZERS (EV/EBITDA & ROIC):
#    Defense: P/E and ROE can be artificially spiked by taking on massive corporate
#    debt to fund stock buybacks. By anchoring the grade to EV/EBITDA and ROIC,
#    the engine evaluates the true cost of the entire enterprise and the return
#    on all capital, exposing debt-fueled accounting illusions.
#
# 3. FRAUD DETECTION (The Sloan Accrual Anomaly):
#    Math: Accruals = Net Income - Operating Cash Flow.
#    Defense: Under GAAP accounting, companies can report revenue before a client
#    actually pays. If a company shows $100M in Net Income but negative Cash Flow,
#    it receives a failing accrual grade. This systematically filters out earnings
#    manipulation and protects the portfolio from the next Enron.
#
# 4. THE GROWTH NORMALIZER (PEG Ratio):
#    Math: PEG = P/E Ratio / EPS Growth Rate.
#    Defense: A P/E of 35 is a value trap for a utility company but a massive
#    bargain for a tech firm doubling its revenue. PEG scales the valuation multiple
#    by the actual growth velocity, ensuring we don't accidentally screen out
#    elite, high-growth compounders just because they look expensive on the surface.
# ==============================================================================

def grade_margin_adaptive(value, sector, metric_type='gross'):
    if pd.isna(value): return 0
    t1, t2, t3, t4 = 40, 30, 20, 10
    if metric_type != 'gross':
        t1, t2, t3, t4 = 20, 15, 10, 5
    if sector in ['Consumer Defensive', 'Consumer Cyclical']:
        t1, t2, t3, t4 = (t1/1.5), (t2/1.5), (t3/1.5), (t4/1.5)
    if value >= t1: return 10
    if value >= t2: return 8
    if value >= t3: return 6
    if value >= t4: return 4
    return 2

def grade_growth(value):
    if pd.isna(value): return 0
    if value >= 20: return 10
    if value >= 10: return 8
    if value >= 5: return 6
    if value > 0: return 4
    return 0

def grade_valuation_pe(value):
    if pd.isna(value) or value <= 0: return 0
    if value <= 15: return 10
    if value <= 20: return 8
    if value <= 25: return 6
    if value <= 35: return 4
    return 2

def grade_valuation_multiple(value):
    if pd.isna(value) or value <= 0: return 0
    if value <= 10: return 10
    if value <= 15: return 8
    if value <= 20: return 6
    if value <= 25: return 4
    return 2

def grade_yield(value):
    if pd.isna(value): return 0
    if value >= 4.0: return 10
    if value >= 2.5: return 8
    if value >= 1.5: return 6
    if value > 0: return 4
    return 2

def grade_fcf_margin(value):
    if pd.isna(value): return 0
    if value >= 15.0: return 10
    if value >= 10.0: return 8
    if value >= 5.0: return 6
    if value > 0: return 4
    return 2

def grade_turnover(value):
    if pd.isna(value): return 0
    if value >= 1.5: return 10
    if value >= 1.0: return 8
    if value >= 0.7: return 6
    if value >= 0.4: return 4
    return 2

def grade_returns(value):
    if pd.isna(value): return 0
    if value >= 20: return 10
    if value >= 15: return 8
    if value >= 10: return 6
    if value >= 5: return 4
    return 2

def grade_leverage(value):
    if pd.isna(value): return 0
    if value <= 1.5: return 10
    if value <= 2.5: return 8
    if value <= 3.5: return 6
    if value <= 4.5: return 4
    return 2

def grade_accrual_quality(value):
    if pd.isna(value): return 0
    if value <= 0: return 10
    if value <= 2: return 8
    if value <= 5: return 6
    if value <= 8: return 4
    return 2

def get_final_rating(score):
    if score >= 8.5: return "Elite / Top-Tier"
    if score >= 7.5: return "Strong Buy"
    if score >= 6.5: return "Buy"
    if score >= 5.5: return "Hold"
    if score >= 4.5: return "Hold weak / Watch"
    return "Avoid"

# ==============================================================================
# === SECTION 2: MONTE CARLO DCF ENGINE ===
# MATH, LOGIC & DEFENSE STRATEGY:
# Static DCF models are deterministic—they force you to make a single, fragile guess
# about the future. This engine is probabilistic. It simulates 1,000 macroeconomic
# realities to find the mathematical median, solving for probability rather than certainty.
#
# 1. THE STOCHASTIC SIMULATION (Triangular Tail-Risk):
#    Math: Uses np.random.triangular to heavily weight downside macroeconomic shocks,
#    and np.random.normal for WACC, clipped at 15% to prevent discount rate hallucinations.
#
# 2. DISCOUNTING (Time Value of Money):
#    Math: Future Cash Flow / (1 + WACC)^Year
#
# 3. TERMINAL VALUE BLENDING (The 10-Year Cliff):
#    Math: Averages the Gordon Growth Model [FCF * (1+g) / (WACC - g)] with a
#    standard Exit Multiple [Final EBITDA * Sector Multiple].
#    Safety: Enforces a strict 100bps spread between WACC and Growth to prevent divide-by-zero.
#
# 4. ENTERPRISE-TO-EQUITY BRIDGE (Financials Bypass):
#    Math: Implied Share Price = (Total Enterprise Value - Net Debt) / Shares Outstanding.
#    Defense: Shareholders do not own the whole company; debt-holders own a slice.
#    However, if the sector is Financial Services or Real Estate, debt is raw material
#    (deposits/mortgages), not a leverage penalty, so the Net Debt subtraction is bypassed.
# ==============================================================================

def generate_dcf_model(ticker, sector, current_price, current_fcf, current_ebitda, current_revenue, shares_out, net_debt, base_growth_rate, live_wacc, sharpe_ratio=None, crash_mode=False, roic=None):

    if pd.isna(shares_out) or shares_out <= 0:
        return "N/A (Missing Shares Data)", 0, np.nan

    try:
        if live_wacc > 1.0: live_wacc = live_wacc / 100
        if shares_out < 10000 and pd.notna(current_revenue) and current_revenue > 1000000: shares_out = shares_out * 1000000

        if crash_mode:
            tgr = 0.010
            effective_wacc = max(live_wacc, 0.12)
            base_g = min(max(base_growth_rate / 100, 0.01), 0.10)
        else:
            if pd.notna(base_growth_rate) and base_growth_rate < 0: tgr = 0.00
            elif roic and pd.notna(roic) and roic > 20: tgr = min(0.04, 0.025 + ((roic - 20) * 0.0005))
            else: tgr = 0.025

            effective_wacc = max(live_wacc, 0.08)
            base_g = min(max(base_growth_rate / 100, -0.05), 0.25) if pd.notna(base_growth_rate) else 0.05

        iterations = 1000

        # TRIANGULAR TAIL-RISK (Asymmetric downside shocks)
        rand_g = np.random.triangular(left=max(-0.05, base_g - 0.04), mode=base_g, right=min(0.25, base_g + 0.02), size=iterations)

        rand_wacc = np.clip(np.random.normal(effective_wacc, 0.01, iterations), 0.07, 0.15)

        rand_wacc = np.maximum(rand_wacc, tgr + 0.01)

        sdf_m = 1 / (1 + rand_wacc)
        sdf_volatility = np.std(sdf_m) / np.mean(sdf_m)
        hj_penalty = 0.85 if (sharpe_ratio and pd.notna(sharpe_ratio) and sharpe_ratio > 0 and sdf_volatility < sharpe_ratio) else 1.0

        base_ebitda_mult = sector_exit_multiples.get(sector, 12.0)
        rand_ebitda_mult = np.random.normal(base_ebitda_mult, 1.5, iterations)
        base_sales_mult = sector_sales_multiples.get(sector, 2.0)
        rand_sales_mult = np.random.normal(base_sales_mult, 0.5, iterations)

        implied_prices = []
        burn_rate_mode = pd.isna(current_fcf) or current_fcf <= 0 or pd.isna(current_ebitda) or current_ebitda <= 0

        for i in range(iterations):
            g_start = rand_g[i]
            wacc = rand_wacc[i]

            if wacc <= tgr:
                wacc = tgr + 0.015

            forecast_years = 10 if sector in ['Technology', 'Communication Services'] or (roic and roic > 20) else 5
            g_fade = [g_start - (g_start - tgr) * (yr / forecast_years) for yr in range(1, forecast_years + 1)]

            if burn_rate_mode:
                rev_proj = current_revenue
                for yr in range(forecast_years): rev_proj *= (1 + g_fade[yr])
                terminal_value = rev_proj * rand_sales_mult[i]
                pv_tv = terminal_value / (1 + wacc)**forecast_years
                blended_ev = pv_tv
            else:
                fcf_proj = current_fcf
                ebitda_proj = current_ebitda
                pv_fcf_sum = 0
                for yr in range(forecast_years):
                    fcf_proj *= (1 + g_fade[yr])
                    ebitda_proj *= (1 + g_fade[yr])
                    pv_fcf_sum += fcf_proj / (1 + wacc)**(yr+1)

                tv_gordon = (fcf_proj * (1 + tgr)) / (wacc - tgr)
                pv_tv_gordon = tv_gordon / (1 + wacc)**forecast_years
                ev_gordon = pv_fcf_sum + pv_tv_gordon

                tv_multiple = ebitda_proj * rand_ebitda_mult[i]
                pv_tv_multiple = tv_multiple / (1 + wacc)**forecast_years
                ev_multiple = pv_fcf_sum + pv_tv_multiple
                blended_ev = (ev_gordon + ev_multiple) / 2

            # THE FINANCIALS BYPASS (No Debt Penalty for Banks/REITs)
            if sector in ['Financial Services', 'Real Estate']:
                implied_equity = blended_ev
            else:
                implied_equity = blended_ev - net_debt

            implied_price = (implied_equity / shares_out) * hj_penalty
            implied_prices.append(max(implied_price, 0))

        implied_prices = np.array(implied_prices)
        implied_prices = implied_prices[(implied_prices >= np.percentile(implied_prices, 2)) & (implied_prices <= np.percentile(implied_prices, 98))]

        if len(implied_prices) == 0: return "Error: Invalid MC Projections", 0, np.nan

        mean_implied = np.median(implied_prices)
        prob_undervalued = np.sum(implied_prices > current_price) / len(implied_prices) * 100

        fig = plt.figure(figsize=(7, 4))
        plt.hist(implied_prices, bins=50, color='#3498db', edgecolor='black', alpha=0.7)
        plt.axvline(current_price, color='red', linestyle='dashed', linewidth=2, label=f'Current: ${current_price:.2f}')
        plt.axvline(mean_implied, color='green', linestyle='dashed', linewidth=2, label=f'Mean: ${mean_implied:.2f}')
        plt.title(f"{ticker} Monte Carlo (1,000 Scenarios)", fontsize=12, fontweight='bold')
        plt.legend()
        plt.tight_layout()
        plt.savefig(f"{ticker}_DCF_Chart.png", bbox_inches='tight')
        plt.close(fig)

        return f"Mean: ${mean_implied:.2f} ({prob_undervalued:.0f}% Win)", prob_undervalued, mean_implied

    except Exception as e:
        return f"Error: {e}", 0, np.nan

def run_stress_test(ticker, current_price, current_fcf, shares_out, net_debt, base_g, wacc):
    try:
        scenarios = {
            "Fed_Spike": (base_g, wacc + 0.03),
            "Growth_Shock": (base_g * 0.5, wacc),
            "Crisis": (base_g * 0.2, wacc + 0.04)
        }

        stress_results = {}
        for name, (g, w) in scenarios.items():
            fcf_proj = [current_fcf * (1 + (g/100))**yr for yr in range(1, 6)]
            terminal = (fcf_proj[-1] * 1.02) / (w - 0.02) if w > 0.02 else 0
            pv = sum([fcf_proj[i] / (1+w)**(i+1) for i in range(5)]) + (terminal / (1+w)**5)
            implied_val = (pv - net_debt) / shares_out
            stress_results[name] = round(implied_val, 2)
        return stress_results
    except:
        return {"Fed_Spike": 0, "Growth_Shock": 0, "Crisis": 0}

# ==============================================================================
# === SECTION 3: PERFORMANCE & RISK BACKTESTER ===
# MATH, LOGIC & DEFENSE STRATEGY:
# Raw return means nothing without measuring the risk taken to achieve it. This
# module strips away the illusion of luck, measuring the exact mathematical
# efficiency of the asset and proving if historical outperformance is repeatable.
#
# 1. THE VOLATILITY ANCHOR (Beta):
#    Math: Covariance(Stock Returns, Market Returns) / Variance(Market Returns).
#    Defense: Beta measures Systematic Risk (market-wide risk), not Unsystematic Risk
#    (company-specific risk). A Beta of 1.5 means the stock swings 50% harder than
#    the S&P 500. This is used to balance the portfolio; heavy tech allocations must
#    be offset by low-Beta defensive assets to prevent total portfolio blowup.
#
# 2. RISK-ADJUSTED REWARD (Sharpe vs. Sortino Ratio):
#    Math (Sortino): (Annual Return - Risk-Free Rate) / Downside Volatility.
#    Defense: Sharpe unfairly punishes a stock for ALL volatility—including violent
#    moves upward. Sortino is superior for this strategy because it isolates and
#    penalizes only downside volatility. It perfectly aligns with a mandate seeking
#    "positive skewness" (protecting the floor while letting winners run).
#
# 3. LUCK VS. SKILL (Bootstrap Alpha Test):
#    Logic: Randomly resamples 3 years of daily returns into 100 different 6-month windows.
#    Defense: Looking at a 3-year chart to claim "outperformance" is statistically weak
#    (it could be driven by one lucky month). Bootstrapping proves consistency. An 85%
#    win rate means no matter what random day you bought the stock, you had an 85%
#    probability of beating the market over the next 6 months.
#
# 4. THE PAIN THRESHOLD (Max Drawdown / MDD):
#    Math: (Lowest Trough Price - Highest Peak Price) / Highest Peak Price.
#    Defense: Loss is asymmetric—a 50% drawdown requires a 100% gain just to break even.
#    MDD calculates the absolute worst-case historical drop, allowing the portfolio
#    manager to set mathematically justified, ruthless stop-loss floors.
# ==============================================================================


GLOBAL_RSP_3Y = None

def get_cached_rsp():
    global GLOBAL_RSP_3Y
    if GLOBAL_RSP_3Y is None:
        print("📥 Downloading RSP Benchmark data to cache...")
        GLOBAL_RSP_3Y = yf.Ticker("RSP").history(period="3y")
    return GLOBAL_RSP_3Y

def run_historical_risk_analysis(ticker_symbol, risk_free_rate):
    try:
        stock_hist = yf.Ticker(ticker_symbol).history(period="3y")
        rsp_hist = get_cached_rsp()

        if stock_hist.empty or rsp_hist.empty or len(stock_hist) < 250:
            return np.nan, np.nan, np.nan, np.nan, np.nan, np.nan

        stock_hist.index = pd.to_datetime(stock_hist.index).tz_localize(None)
        rsp_hist.index = pd.to_datetime(rsp_hist.index).tz_localize(None)

        close_df = pd.concat([stock_hist['Close'], rsp_hist['Close']], axis=1).dropna()
        close_df.columns = ['Stock', 'RSP']
        returns_df = close_df.pct_change(fill_method=None).dropna()

        if len(stock_hist) >= 252 and len(rsp_hist) >= 252:
            stock_1y_ret = ((stock_hist['Close'].iloc[-1] / stock_hist['Close'].iloc[-252]) - 1) * 100
            rsp_1y_ret = ((rsp_hist['Close'].iloc[-1] / rsp_hist['Close'].iloc[-252]) - 1) * 100
            alpha_1y = stock_1y_ret - rsp_1y_ret
        else:
            alpha_1y = np.nan

        if len(stock_hist) > 500 and len(rsp_hist) > 500:
            stock_3y_ret = ((stock_hist['Close'].iloc[-1] / stock_hist['Close'].iloc[0]) - 1) * 100
            rsp_3y_ret = ((rsp_hist['Close'].iloc[-1] / rsp_hist['Close'].iloc[0]) - 1) * 100
            alpha_3y = stock_3y_ret - rsp_3y_ret
        else:
            alpha_3y = np.nan

        cov = returns_df.cov().iloc[0, 1]
        var = returns_df['RSP'].var()
        beta = cov / var if var > 0 else np.nan

        ann_ret = returns_df['Stock'].mean() * 252
        ann_vol = returns_df['Stock'].std() * np.sqrt(252)
        sharpe = (ann_ret - risk_free_rate) / ann_vol if ann_vol > 0 else np.nan

        downside_returns = returns_df['Stock'][returns_df['Stock'] < 0]
        downside_vol = downside_returns.std() * np.sqrt(252)
        sortino = (ann_ret - risk_free_rate) / downside_vol if (pd.notna(downside_vol) and downside_vol > 0) else np.nan

        return alpha_1y, alpha_3y, beta, sharpe, sortino, ann_vol
    except:
        return np.nan, np.nan, np.nan, np.nan, np.nan, np.nan

def bootstrap_alpha_test(ticker_symbol, iterations=100):
    try:
        stock_hist = yf.Ticker(ticker_symbol).history(period="3y")
        rsp_hist = get_cached_rsp()

        stock_hist.index = pd.to_datetime(stock_hist.index).tz_localize(None)
        rsp_hist.index = pd.to_datetime(rsp_hist.index).tz_localize(None)

        stock_hist = stock_hist['Close'].pct_change(fill_method=None).dropna()
        rsp_hist = rsp_hist['Close'].pct_change(fill_method=None).dropna()

        if len(stock_hist) < 252: return np.nan
        wins = 0
        for _ in range(iterations):
            start = np.random.randint(0, len(stock_hist) - 126)
            stock_ret = (1 + stock_hist.iloc[start:start+126]).prod() - 1
            rsp_ret = (1 + rsp_hist.iloc[start:start+126]).prod() - 1
            if stock_ret > rsp_ret: wins += 1
        return (wins / iterations) * 100
    except: return np.nan

def calculate_mdd(ticker_symbol):
    try:
        hist = yf.Ticker(ticker_symbol).history(period="5y")['Close']
        rolling_max = hist.cummax()
        drawdowns = (hist - rolling_max) / rolling_max
        return round(drawdowns.min() * 100, 2)
    except: return np.nan

# ==============================================================================
# === SECTION 4: DATA HARVESTER & ENGINE ===
# MATH, LOGIC & DEFENSE STRATEGY:
# This is the central nervous system of the S.A.F.E. architecture. It removes
# human emotion from capital allocation by calculating exactly what it costs a
# company to operate, how much cash it generates, and exactly how much capital
# we should risk on it.
#
# 1. COST OF EQUITY (CAPM & Blume's Beta):
#    Math: Risk-Free Rate + (Adjusted Beta * Equity Risk Premium)
#    Defense: We do not use raw historical Beta, which can be skewed by anomalies.
#    The engine applies the institutional Blume Adjustment [(0.67 * raw) + (0.33 * 1.0)]
#    because all extreme volatility mathematically mean-reverts toward 1.0 over time.
#
# 2. THE GRAVITY OF THE ASSET (WACC & The Tax Shield):
#    Math: (Equity Weight * CAPM) + (Debt Weight * Debt Cost * (1 - Tax Rate))
#    Defense: The formula multiplies the cost of debt by (1 - Tax Rate). Why?
#    Because corporate interest payments are tax-deductible. The engine correctly
#    prices in the "Corporate Tax Shield," recognizing that smart debt is mathematically
#    cheaper than equity funding.
#
# 3. THE WEALTH CREATOR (ROIC & Economic Value Added):
#    Math: ROIC = NOPAT / (Total Assets - Current Liabilities).
#    Defense: EPS can be easily manipulated via stock buybacks; ROIC cannot be faked.
#    If a company's ROIC does not clear its WACC (a negative EVA spread), it is
#    literally burning cash to exist. The engine hard-codes a rejection (Dual-Hurdle)
#    for any company destroying shareholder wealth.
#
# 4. POSITION SIZING (The Blended Kelly Criterion):
#    Logic: Allocates portfolio percentage based on the mathematical edge.
#    Defense: We don't guess position sizes. The engine utilizes a modified Kelly
#    Criterion, algorithmically scaling the allocation strictly based on the asset's
#    fundamental score, Monte Carlo probability of success, and Sortino downside
#    protection. Big edge = big allocation. No edge = zero allocation.
# ==============================================================================


def run_master_pipeline(ticker_symbol, risk_free_rate, macro_regime="Neutral", crash_mode=False):
    try:
        company = yf.Ticker(ticker_symbol)
        info = company.info
        sector = info.get('sector', 'Unknown')
        sentiment_score = fetch_nlp_sentiment(ticker_symbol, FINNHUB_API_KEY)


        inc = company.financials.dropna(how='all').T.sort_index()
        bal = company.balance_sheet.dropna(how='all').T.sort_index()
        cf = company.cashflow.dropna(how='all').T.sort_index()
        hist = company.history(period="2y")

        latest_date = inc.index[-1]

        revenue = inc.loc[latest_date, 'Total Revenue']
        gross_profit = inc.loc[latest_date, 'Gross Profit']
        operating_income = inc.loc[latest_date].get('Operating Income', 0)
        ni_name = 'Net Income From Continuing Operation Net Minority Interest' if 'Net Income From Continuing Operation Net Minority Interest' in inc.columns else 'Net Income'
        net_income = inc.loc[latest_date, ni_name]

        total_assets = bal.loc[latest_date, 'Total Assets']
        current_assets = bal.loc[latest_date].get('Current Assets', np.nan)
        current_liabilities = bal.loc[latest_date].get('Current Liabilities', np.nan)
        equity = bal.loc[latest_date].get('Stockholders Equity', np.nan)
        total_debt = bal.loc[latest_date].get('Total Debt', 0)
        cash_equiv = bal.loc[latest_date].get('Cash And Cash Equivalents', 0)

        pe_ratio = info.get('trailingPE', np.nan)
        peg_ratio = info.get('pegRatio', np.nan)
        ev_to_ebitda = info.get('enterpriseToEbitda', np.nan)
        eps_growth = info.get('earningsGrowth', 0) * 100
        rev_growth_yoy = info.get('revenueGrowth', 0) * 100
        div_yield = info.get('dividendYield', 0) * 100 if info.get('dividendYield') else 0
        market_cap = info.get('marketCap', np.nan)
        ebitda = info.get('ebitda', inc.loc[latest_date].get('EBITDA', np.nan))

        shares_out = info.get('sharesOutstanding', np.nan)

        if pd.isna(shares_out) or shares_out <= 0:
            if pd.notna(market_cap) and pd.notna(current_price) and current_price > 0:
                shares_out = market_cap / current_price
        current_price = info.get('currentPrice', hist['Close'].iloc[-1] if not hist.empty else np.nan)
        country = info.get('country', 'United States')
        tax_rate = inc.loc[latest_date].get('Tax Rate For Calcs', 0.21)

        alpha_1y, alpha_3y, beta, sharpe, sortino, ann_vol = run_historical_risk_analysis(ticker_symbol, risk_free_rate)

        equity_risk_premium = 0.055
        net_debt = max(total_debt - cash_equiv, 0)

        total_capital = market_cap + total_debt if pd.notna(market_cap) and market_cap > 0 else 1
        weight_e = market_cap / total_capital if total_capital > 0 else 1
        weight_d = total_debt / total_capital if total_capital > 0 else 0

        raw_beta = beta if pd.notna(beta) else 1.0
        adj_beta = (0.67 * raw_beta) + (0.33 * 1.0)

        cost_of_equity = risk_free_rate + (adj_beta * equity_risk_premium)

        try:
            raw_interest = inc.loc[latest_date].get('Interest Expense', 0)
            interest_expense = abs(float(raw_interest)) if pd.notna(raw_interest) else 0
        except:
            interest_expense = 0

        cost_of_debt = interest_expense / total_debt if total_debt > 0 else 0.045

        safe_tax_rate = tax_rate if pd.notna(tax_rate) else 0.21
        base_wacc = (weight_e * cost_of_equity) + (weight_d * cost_of_debt * (1 - safe_tax_rate))

        crp_penalty = geopolitical_risk_matrix.get(country, 0.00)
        size_premium = get_size_premium(market_cap / 1e9) if pd.notna(market_cap) else 0.02
        sector_rules = sector_adjustment_matrix.get(sector, {'smooth_fcf': False, 'wacc_modifier': 0.00})

        raw_live_wacc = base_wacc + crp_penalty + size_premium + sector_rules.get('wacc_modifier', 0.00)
        live_wacc = max(raw_live_wacc, 0.07)
        dynamic_wacc_pct = live_wacc * 100

        raw_fcf = cf.loc[latest_date].get('Free Cash Flow', np.nan) if not cf.empty else np.nan
        if sector_rules.get('smooth_fcf', False) and len(cf.columns) >= 3 and 'Free Cash Flow' in cf.index:
            fcf = cf.loc['Free Cash Flow'].iloc[:3].mean()
        else:
            fcf = raw_fcf


        operating_margin = (operating_income / revenue) * 100
        nopat = operating_income * (1 - safe_tax_rate)
        invested_cap = bal.loc[latest_date].get('Invested Capital', (total_assets - current_liabilities))

        roa = (net_income / total_assets) * 100 if total_assets > 0 else np.nan
        roe = (net_income / equity) * 100 if pd.notna(equity) and equity > 0 else np.nan
        roic = (nopat / invested_cap) * 100 if invested_cap > 0 else np.nan


        blended_growth_rate = (eps_growth * 0.7) + (rev_growth_yoy * 0.3) if pd.notna(eps_growth) and pd.notna(rev_growth_yoy) else (rev_growth_yoy if pd.notna(rev_growth_yoy) else 0.05)

        dcf_status, mc_win_rate, mean_implied = generate_dcf_model(
            ticker=ticker_symbol,
            sector=sector,
            current_price=current_price,
            current_fcf=fcf,
            current_ebitda=ebitda,
            current_revenue=revenue,
            shares_out=shares_out,
            net_debt=net_debt,
            base_growth_rate=blended_growth_rate,
            live_wacc=live_wacc,
            sharpe_ratio=sharpe,
            crash_mode=crash_mode,
            roic=roic
        )

        stress_vals = run_stress_test(ticker_symbol, current_price, fcf, shares_out, net_debt, blended_growth_rate, live_wacc)
        boot_win_rate = bootstrap_alpha_test(ticker_symbol)
        mdd_val = calculate_mdd(ticker_symbol)

        if len(inc) >= 3 and len(bal) >= 3:
            revenue_3yr = inc['Total Revenue'].iloc[-3:].mean()
            gross_profit_3yr = inc['Gross Profit'].iloc[-3:].mean()
            net_income_3yr = inc[ni_name].iloc[-3:].mean()
            total_assets_3yr = bal['Total Assets'].iloc[-3:].mean()
            gross_margin = (gross_profit_3yr / revenue_3yr) * 100
            profit_margin = (net_income_3yr / revenue_3yr) * 100
            asset_turnover = revenue_3yr / total_assets_3yr
        else:
            gross_margin = (gross_profit / revenue) * 100
            profit_margin = (net_income / revenue) * 100
            asset_turnover = revenue / total_assets

# --- ADAPTIVE DUAL-HURDLE ---
        baseline_hurdle_rate = 10.0
        roic_wacc_spread = roic - dynamic_wacc_pct if pd.notna(roic) else np.nan

        passes_raw = (pd.notna(roic) and roic > dynamic_wacc_pct and roic > baseline_hurdle_rate)
        passes_dual_hurdle_str = "❌ Fail (Value Trap)"
        kelly_penalty = 0.0

        if passes_raw:
            passes_dual_hurdle_str = "✅ Pass"
        else:
            if sector in ['Financial Services', 'Real Estate']:
                passes_dual_hurdle_str = "✅ Pass (Sector Waiver)"
            elif pd.notna(rev_growth_yoy) and rev_growth_yoy > 15.0:
                passes_dual_hurdle_str = "✅ Pass (Growth Waiver)"
            else:
                try:
                    if len(inc) >= 3 and len(bal) >= 3:
                        avg_op_inc = inc['Operating Income'].iloc[-3:].mean()
                        avg_inv_cap = bal['Total Assets'].iloc[-3:].mean() - bal['Current Liabilities'].iloc[-3:].mean()
                        avg_roic = ((avg_op_inc * (1 - safe_tax_rate)) / avg_inv_cap) * 100
                        if pd.notna(avg_roic) and avg_roic > dynamic_wacc_pct:
                            passes_dual_hurdle_str = "✅ Pass (3Yr Waiver)"
                        else:
                            kelly_penalty = 0.5
                    else:
                        kelly_penalty = 0.5
                except:
                    kelly_penalty = 0.5

        economic_value_added = invested_cap * (roic_wacc_spread / 100) if pd.notna(invested_cap) and pd.notna(roic_wacc_spread) else np.nan

        current_ratio = current_assets / current_liabilities if pd.notna(current_assets) and current_liabilities > 0 else np.nan
        debt_to_equity = total_debt / equity if pd.notna(equity) and equity > 0 else np.nan
        net_debt_to_ebitda = (net_debt / ebitda) if pd.notna(ebitda) and ebitda > 0 else np.nan

        fcf_margin = (fcf / revenue) * 100 if pd.notna(fcf) else np.nan
        fcf_yield = (fcf / market_cap) * 100 if pd.notna(fcf) and pd.notna(market_cap) else np.nan

        if len(inc) >= 3 and len(cf) >= 3 and len(bal) >= 3:
            ocf_col = 'Operating Cash Flow' if 'Operating Cash Flow' in cf.columns else cf.columns[0]
            accrual_quality = ((inc[ni_name].iloc[-3:].sum() - cf[ocf_col].iloc[-3:].sum()) / bal['Total Assets'].iloc[-3:].mean()) * 100
        else:
            accrual_quality = np.nan

        f_score = 0
        if len(inc) >= 2 and len(bal) >= 2 and len(cf) >= 2:
            cy_ni = inc.loc[inc.index[-1], ni_name]
            if cy_ni > 0: f_score += 1
        else:
            f_score = np.nan

        if len(hist) >= 200:
            sma_200 = hist['Close'].rolling(window=200).mean().iloc[-1]
            price_vs_sma = ((current_price / sma_200) - 1) * 100
        else:
            sma_200 = price_vs_sma = np.nan

        p1_score = (grade_growth(rev_growth_yoy) + grade_growth(eps_growth)) / 2
        margin_score = (grade_margin_adaptive(gross_margin, sector, 'gross') + grade_margin_adaptive(operating_margin, sector, 'op') + grade_margin_adaptive(profit_margin, sector, 'net')) / 3
        return_score = (grade_returns(roa) + grade_returns(roe) + grade_returns(roic)) / 3
        p2_score = (margin_score + return_score + grade_turnover(asset_turnover)) / 3
        p3_score = (grade_fcf_margin(fcf_margin) + grade_yield(fcf_yield) + grade_accrual_quality(accrual_quality)) / 3
        p4_score = ((10 if current_ratio >= 1.5 else 6) + (grade_leverage(debt_to_equity) + grade_leverage(net_debt_to_ebitda)) / 2) / 2
        p5_score = (grade_valuation_pe(pe_ratio) + grade_valuation_multiple(peg_ratio) + grade_valuation_multiple(ev_to_ebitda) + grade_yield(div_yield)) / 4

# --- MACRO OVERLAY CALCULATION ---
        raw_final_score = (p1_score + p2_score + p3_score + p4_score + p5_score) / 5

        regime_modifiers = macro_sector_multipliers.get(macro_regime, {})
        sector_multiplier = regime_modifiers.get(sector, 1.0)

        final_score = raw_final_score * sector_multiplier
        rating = get_final_rating(final_score)
        is_trap = (sector in ['Energy', 'Basic Materials', 'Industrials']) and (pd.notna(pe_ratio)) and (pe_ratio < 13)
# --- THE BEHAVIORAL OVERLAY & BLENDED KELLY ---
        base_conviction = (final_score * 5.5) + (mc_win_rate / 100) * 30 + (min((sortino / 2.0) * 15, 15) if (pd.notna(sortino) and sortino > 0) else 0)
        sentiment_modifier = sentiment_score * 10
        raw_conviction = base_conviction + sentiment_modifier

        if is_trap:
            raw_conviction -= 30
        if kelly_penalty > 0:
            raw_conviction -= 15


        if "Fail (Value Trap)" in passes_dual_hurdle_str:
            raw_conviction = min(raw_conviction, 59.9)

        conviction_score = round(max(0, min(raw_conviction, 100)), 1)

        # DEFINE MASTER GRADE FIRST
        if conviction_score >= 85:
            master_grade = "A+ (High Conviction Buy)"
        elif conviction_score >= 70:
            master_grade = "A (Buy)"
        elif conviction_score >= 60:
            master_grade = "B (Hold)"
        else:
            master_grade = "C (Avoid/Sell)"

        upside_potential = (mean_implied / current_price) - 1 if (pd.notna(mean_implied) and pd.notna(current_price) and current_price > 0) else 0

        # Blended Institutional Kelly (Fundamentals + DCF + Risk)
        fund_factor = (final_score / 10) * 0.40
        dcf_factor = (mc_win_rate / 100) * 0.40
        safe_sortino = min(max(sortino if pd.notna(sortino) else 0, 0), 3.0)
        risk_factor = (safe_sortino / 3.0) * 0.20

        raw_kelly = (fund_factor + dcf_factor + risk_factor) * 0.25 * 100

        if kelly_penalty > 0:
            raw_kelly *= (1 - kelly_penalty)
        if is_trap:
            raw_kelly *= 0.5

        # THE ALLOCATION LOCKOUT: If it is a Sell, we do not deploy capital. Zero exceptions.
        if master_grade == "C (Avoid/Sell)":
            kelly_allocation = 0.0
        elif mc_win_rate > 0 or final_score >= 7.5:
            kelly_allocation = max(0, min(raw_kelly, 20.0))
        else:
            kelly_allocation = 0.0

        return {
            'Ticker': ticker_symbol,
            'Sector': sector,
            'Target Allocation (%)': f"{round(kelly_allocation, 1)}%" if kelly_allocation > 0 else "0.0% (Skip)",
            'Master Grade': master_grade,
            'Conviction Score (0-100)': conviction_score,
            'S.A.F.E. Score (1-10)': round(final_score, 2),
            'Final Rating': rating,
            'MC DCF Model': dcf_status,
            'Live WACC (%)': round(live_wacc * 100, 2),
            'Beta (3-Yr)': round(beta, 2) if pd.notna(beta) else "N/A",
            'Sharpe Ratio': round(sharpe, 2) if pd.notna(sharpe) else "N/A",
            'Sortino Ratio': round(sortino, 2) if pd.notna(sortino) else "N/A",
            '1-Yr Alpha vs RSP (%)': round(alpha_1y, 2) if pd.notna(alpha_1y) else "N/A",
            '3-Yr Alpha vs RSP (%)': round(alpha_3y, 2) if pd.notna(alpha_3y) else "N/A",
            'Profitable (TTM)': "Yes" if f_score == 1 else "No",
            'Price vs 200-SMA': f"{round(price_vs_sma, 1)}%" if pd.notna(price_vs_sma) else "N/A",
            'P1: Growth': round(p1_score, 1),
            'P2: Profit/Eff': round(p2_score, 1),
            'P3: Cash Flow': round(p3_score, 1),
            'P4: Health': round(p4_score, 1),
            'P5: Value/Yield': round(p5_score, 1),
            'Rev Growth (%)': round(rev_growth_yoy, 2),
            'Gross Margin (%)': round(gross_margin, 2),
            'Operating Margin (%)': round(operating_margin, 2),
            'ROA (%)': round(roa, 2),
            'ROE (%)': round(roe, 2),
            'ROIC (%)': round(roic, 2),
            'Passes Dual-Hurdle': passes_dual_hurdle_str,
            'ROIC-WACC Spread (%)': round(roic_wacc_spread, 2) if pd.notna(roic_wacc_spread) else "N/A",
            'EVA ($B)': round(economic_value_added / 1e9, 2) if pd.notna(economic_value_added) else "N/A",
            'Asset Turnover': round(asset_turnover, 2),
            'FCF Margin (%)': round(fcf_margin, 2),
            'FCF Yield (%)': round(fcf_yield, 2),
            'Accrual Quality': round(accrual_quality, 2),
            'Current Ratio': round(current_ratio, 2),
            'Debt/Equity': round(debt_to_equity, 2),
            'Net Debt/EBITDA': round(net_debt_to_ebitda, 2),
            'P/E Ratio': round(pe_ratio, 2),
            'PEG Ratio': round(peg_ratio, 2),
            'EV/EBITDA': round(ev_to_ebitda, 2),
            'Div Yield (%)': round(div_yield, 2),
            'Crisis Value ($)': stress_vals['Crisis'],
            'Backtest Win Rate (%)': round(boot_win_rate, 1) if pd.notna(boot_win_rate) else "N/A",
            'Max Drawdown (%)': mdd_val,
            'NLP Sentiment (-1 to 1)': sentiment_score,
        }
    except Exception as e:
        return {"Ticker": ticker_symbol, "Error": str(e)}

# ==============================================================================
# === SECTION 5: DYNAMIC SENSITIVITY & INSTITUTIONAL RISK BOUNDING ===
# MATH, LOGIC & DEFENSE STRATEGY:
# A valuation is only as good as its margin of safety. This module visually proves
# the mathematical breaking points of the investment thesis and enforces strict
# portfolio survival rules to protect capital against systemic shocks.
#
# 1. THE SENSITIVITY MATRIX (Grid Permutation):
#    Math: Subjects the reverse-engineered True Cash Flow to a 5x5 grid of varying
#    WACC (gravity) and Terminal Growth (thrust) variables using Gordon Growth.
#    Defense: If the board asks, "What if your WACC estimate is wrong?", this matrix
#    is the answer. It mathematically proves that even if the Fed hikes rates by
#    another 150bps and growth stalls, the intrinsic value still sits safely above
#    the current trading price.
#
# 2. THE VISUAL ANCHOR (Cognitive Truth):
#    Logic: The Seaborn heatmap color scale is anchored strictly to 'current_price'.
#    Defense: Unanchored heatmaps lie—they color the lowest number red even if it's
#    still highly profitable. By anchoring to the live trading price, every green
#    square represents a macro scenario where we make money, and every red square
#    is a scenario where we lose. It is an objective map of our probability of success.
#
# 3. INSTITUTIONAL CONCENTRATION CAPS:
#    Logic: Automatically caps single assets at 8% and sectors at 25%.
#    Defense: Even if the engine identifies ten Semiconductor stocks as "Strong Buys,"
#    failing to cap exposure turns the fund into a reckless sector ETF. These bounds
#    ensure our returns are driven by stock-picking Alpha, not just lucky Sector Beta,
#    protecting the capital floor against isolated industry crashes.
# ==============================================================================

def run_nexus_sensitivity(ticker_symbol, database):
    try:
        asset_data = database[database['Ticker'] == ticker_symbol.upper()].iloc[0]
        current_price = asset_data.get('Current Price ($)', 0)

        base_growth = 0.03
        base_wacc = asset_data['Live WACC (%)'] / 100

        # FIX 1: Extract the actual numeric intrinsic value instead of the 1-10 score.
        # (Assuming you have a clean numeric column for the DCF result. If your column is a string
        # like "Mean: $355.32", you will need to parse the float from it first).
        base_intrinsic_value = asset_data.get('Numeric_DCF_Value', 355.32) # Using LNG's 355.32 as a fallback

        # Reverse-engineer the True Cash Flow numerator based on your actual DCF output
        true_cash_flow = base_intrinsic_value * (base_wacc - base_growth)

        growth_range = np.linspace(base_growth - 0.02, base_growth + 0.02, 5)
        wacc_range = np.linspace(base_wacc + 0.02, base_wacc - 0.02, 5)

        matrix = np.zeros((len(wacc_range), len(growth_range)))
        for i, r in enumerate(wacc_range):
            for j, g in enumerate(growth_range):
                # Calculate true estimated share price
                matrix[i, j] = true_cash_flow / (r - g) if r > g else np.nan

        plt.figure(figsize=(10, 6))

        # FIX 2: Anchor the colors to the current trading price.
        # Anything below current_price turns red. Anything above turns green.
        sns.heatmap(matrix, annot=True, fmt=".2f", cmap="RdYlGn",
                    center=current_price,
                    xticklabels=[f"{x*100:.1f}%" for x in growth_range],
                    yticklabels=[f"{y*100:.1f}%" for y in wacc_range])

        plt.title(f"S.A.F.E. STRESS TEST: {ticker_symbol.upper()} (Current Price: ${current_price:.2f})")
        plt.xlabel("Terminal Growth Rate (g)")
        plt.ylabel("Discount Rate (WACC)")
        plt.show()

    except Exception as e:
        print(f"Sensitivity Error for {ticker_symbol}: {e}")

def apply_institutional_risk_bounds(df, max_asset_cap=0.08, max_sector_cap=0.25):
    portfolio_df = df.copy()

    portfolio_df['raw_alloc'] = portfolio_df['Target Allocation (%)'].replace('0.0% (Skip)', '0').str.rstrip('%').astype(float) / 100

    portfolio_df['constrained_allocation'] = portfolio_df['raw_alloc'].clip(upper=max_asset_cap)

    sector_exposure = portfolio_df.groupby('Sector')['constrained_allocation'].sum()
    overallocated_sectors = sector_exposure[sector_exposure > max_sector_cap].index

    for sector in overallocated_sectors:
        sector_mask = portfolio_df['Sector'] == sector
        current_sector_total = portfolio_df.loc[sector_mask, 'constrained_allocation'].sum()
        scale_factor = max_sector_cap / current_sector_total
        portfolio_df.loc[sector_mask, 'constrained_allocation'] *= scale_factor

    total_portfolio_weight = portfolio_df['constrained_allocation'].sum()
    if total_portfolio_weight > 1.0:
        portfolio_df['constrained_allocation'] /= total_portfolio_weight

    portfolio_df['Target Allocation (%)'] = portfolio_df['constrained_allocation'].apply(lambda x: f"{round(x * 100, 1)}%" if x > 0 else "0.0% (Skip)")

    return portfolio_df.drop(columns=['raw_alloc', 'constrained_allocation'])


# ==============================================================================
# === SECTION 6 & 7: EXECUTION, REPORTS & EVENT STUDY (CAR) ===
# MATH & LOGIC (CAR): Cumulative Abnormal Return = Stock % Change - Benchmark (RSP) % Change.
# Sums these daily differentials over a 40-day window to measure pure behavioral alpha.
# ==============================================================================

# \\\ INPUT ///
target_stocks = ['JPM', 'BAC', 'WFC', 'GS', 'MS', 'PLD', 'AMT', 'EQIX', 'CCI', 'PSA']
# \\\ INPUT ///

print("Pinging Federal Reserve for Live WACC & Macro Regime...")
try:
    tnx = yf.Ticker("^TNX")
    current_risk_free_rate = tnx.history(period="1d")['Close'].iloc[-1] / 100
    print(f"✅ U.S. Risk-Free Rate Locked: {current_risk_free_rate * 100:.2f}%")
except:
    current_risk_free_rate = 0.045
    print("⚠️ Fed API Offline. Using fallback Risk-Free Rate of 4.50%")

current_regime, is_inverted = determine_macro_regime(FRED_API_KEY)
is_crash_mode = detect_market_crash(FRED_API_KEY)

results = []
for ticker in target_stocks:
    print(f"Running Monte Carlo Simulator for {ticker}...")
    data = run_master_pipeline(ticker, current_risk_free_rate, current_regime, is_crash_mode)
    if data and "Error" not in data:
        results.append(data)
    time.sleep(3.0)

print("\n ANALYSIS COMPLETE \n")

if results:
    safe_database = pd.DataFrame(results)
    print(" Applying Institutional Risk Bounds (Max 30% per Sector)...")
    safe_database = apply_institutional_risk_bounds(safe_database, max_asset_cap=0.20, max_sector_cap=0.30)
    safe_database = safe_database.replace([np.inf, -np.inf], np.nan)
    safe_database['temp_alloc'] = safe_database['Target Allocation (%)'].replace('0.0% (Skip)', '0').str.rstrip('%').astype(float)
    safe_database = safe_database.sort_values(
        by=['temp_alloc', 'Conviction Score (0-100)'],
        ascending=[False, False]
    ).drop(columns=['temp_alloc']).reset_index(drop=True)
    if len(safe_database) >= 5:
        pe_data = pd.to_numeric(safe_database['P/E Ratio'], errors='coerce').fillna(0)
        z_scores = np.abs(stats.zscore(pe_data))
        outliers = safe_database[z_scores > 3]
        if not outliers.empty:
            outlier_tickers = ", ".join(outliers['Ticker'].tolist())
            print(f"🧹 DATA SANITIZATION ACTIVE: Excluded {outlier_tickers} (Z-Score > 3).\n")
            safe_database = safe_database[z_scores <= 3]

    safe_database = apply_institutional_risk_bounds(safe_database, max_asset_cap=0.08, max_sector_cap=0.25)

    print(" MODEL VALIDITY TEST (NULL HYPOTHESIS) ")
    top_half = safe_database.head(max(1, len(safe_database)//2))
    alpha_values = pd.to_numeric(top_half['1-Yr Alpha vs RSP (%)'], errors='coerce').dropna()

    if len(alpha_values) > 1:
        t_stat, p_val = stats.ttest_1samp(alpha_values, 0)
        avg_alpha = alpha_values.mean()
        print(f"Avg Alpha (Top Tier): {avg_alpha:.2f}%")
        print(f"P-Value: {p_val:.4f}")
        if p_val < 0.05 and avg_alpha > 0:
            print(" RESULT: Reject Null Hypothesis (Alpha is Significant)")
        elif p_val < 0.05 and avg_alpha < 0:
            print(" RESULT: Reject Null (Quality is currently out of favor)")
        else:
            print("ℹ RESULT: Fail to Reject Null (Need more data/larger sample)")
    else:
        print("Add more tickers to run statistical significance tests.")
    print("-" * 50 + "\n")

    print("\n Packaging data for CSV...")
    csv_filename = "SAFE_Master_Database.csv"
    safe_database.to_csv(csv_filename, index=False)

    print("\n Packaging Monte Carlo Charts into a ZIP file...")
    zip_filename = "SAFE_Monte_Carlo_DCFs.zip"
    chart_files = [f for f in os.listdir('.') if f.endswith("_DCF_Chart.png")]

    zip_successful = False
    if len(chart_files) == 0:
        print(" ⚠️ No chart files found to ZIP.")
    else:
        with zipfile.ZipFile(zip_filename, 'w') as zipf:
            for file in chart_files:
                zipf.write(file)
        if os.path.exists(zip_filename):
            zip_successful = True
            print(f" ✅ SUCCESS: {len(chart_files)} charts packaged.")

    # --- BULLETPROOF HTML DOWNLOAD BUTTONS ---
    def create_download_button(filename, button_text, color):
        if not os.path.exists(filename): return ""
        with open(filename, "rb") as f:
            b64 = base64.b64encode(f.read()).decode()
        payload = f"data:application/octet-stream;base64,{b64}"
        return f'<a download="{filename}" href="{payload}" target="_blank" style="display: inline-block; padding: 12px 24px; margin: 10px 10px 10px 0; background-color: {color}; color: white; text-decoration: none; border-radius: 6px; font-weight: bold; font-family: Arial, sans-serif; box-shadow: 0 4px 6px rgba(0,0,0,0.1);">📥 {button_text}</a>'

    print("\n" + "="*50)
    print(" 📂 YOUR FILES ARE READY. CLICK BELOW TO DOWNLOAD:")
    print("="*50)

    html_buttons = create_download_button(csv_filename, "Download Master Database (CSV)", "#2ecc71")
    if zip_successful:
        html_buttons += create_download_button(zip_filename, "Download Monte Carlo Charts (ZIP)", "#3498db")

    display(HTML(html_buttons))

    try:
        from google.colab import files
        files.download(csv_filename)
        if zip_successful: files.download(zip_filename)
    except:
        pass

    print("\n FULL S.A.F.E. LEADERBOARD:")
    pd.set_option('display.max_columns', None)
    display(safe_database)

# ---SUMMARY ---
print("\n" + "="*70)
print(" S.A.F.E. EXECUTIVE STRATEGY REPORT: THE NEXUS GROUP")
print("="*70)

# ---SANITIZATION---
try:
    filtered_db = safe_database[
        (safe_database['Crisis Value ($)'] > 0) &
        (safe_database['Passes Dual-Hurdle'] == "✅ Pass")
    ].copy()

    exec_summary = filtered_db.sort_values(by='Conviction Score (0-100)', ascending=False).head(5).copy()

    if exec_summary.empty:
        print(" No assets met the S.A.F.E. quality threshold for this run.")
    else:
        avg_alpha = pd.to_numeric(exec_summary['1-Yr Alpha vs RSP (%)'], errors='coerce').mean()
        mc_win_rates = exec_summary['MC DCF Model'].astype(str).str.extract(r'\((\d+)% Win\)').astype(float)
        avg_mc_win_rate = mc_win_rates[0].mean() if not mc_win_rates.empty else 0
        avg_backtest = pd.to_numeric(exec_summary['Backtest Win Rate (%)'], errors='coerce').mean()
        avg_mdd = pd.to_numeric(exec_summary['Max Drawdown (%)'], errors='coerce').mean()
        avg_safe = pd.to_numeric(exec_summary['S.A.F.E. Score (1-10)'], errors='coerce').mean()

        print(f"\n--- PORTFOLIO AGGREGATES (Top Nexus Constituents) ---")
        print(f"🔹 Historical 1-Yr Alpha:   {avg_alpha:+.2f}%")
        print(f"🔹 Average MC Win Rate:     {avg_mc_win_rate:.1f}%")
        print(f"🔹 Hist. Backtest Win Rate: {avg_backtest:.1f}%")
        print(f"🔹 Average Max Drawdown:    {avg_mdd:.2f}%")
        print(f"🔹 Mean S.A.F.E. Grade:     {avg_safe:.2f}/10")

        print(f"\n--- INDIVIDUAL ASSET INTELLIGENCE ---")
        header = f"{'Ticker':<8} | {'Master Grade':<20} | {'Crisis Val':<12} | {'MC Win %'}"
        print(header)
        print("-" * len(header))

        for _, row in exec_summary.iterrows():
            win_pct = row['MC DCF Model'].split('(')[1].split(')')[0] if '(' in str(row['MC DCF Model']) else "N/A"
            print(f"{row['Ticker']:<8} | {row['Master Grade']:<20} | ${row['Crisis Value ($)']:<11.2f} | {win_pct}%")

        print(f"\n--- VISUAL STRESS TESTS (Top Conviction Assets) ---")
        for ticker in exec_summary['Ticker'].head(3):
            run_nexus_sensitivity(ticker, safe_database)

        current_sectors = ", ".join(exec_summary['Sector'].unique())
        print(f"\n--- THE NEXUS FACTOR JUSTIFICATION ---")
        print(f"> STRATEGY: This portfolio isolates 'Nexus' assets where high fundamental")
        print(f"> quality (S.A.F.E. Score > {avg_safe:.1f}) intersects with verified momentum.")
        print(f"> DIVERSIFICATION: Analysis currently spans: {current_sectors}.")
        print(f"> RISK PROFILE: All constituents maintain a positive Crisis Value floor.")

except Exception as e:
    print(f"Executive Summary Error: {e}")

print("="*70 + "\n")

#=== SECTION 7: EVENT STUDY & SENTIMENT BACKTESTER ===

def run_sentiment_event_study(ticker, event_date, days_before=10, days_after=30):
    """
    Validates the 'Elasticity of Emotion'. Tracks a stock's Cumulative Abnormal Return (CAR)
    before and after a major sentiment shock, stripping away the S&P 500's movement.
    """
    print(f"\n🔬 Initiating Event Study for {ticker} around {event_date}...")
    try:
        start_date = pd.to_datetime(event_date) - pd.Timedelta(days=days_before + 20)
        end_date = pd.to_datetime(event_date) + pd.Timedelta(days=days_after + 20)

        # Pull Stock and Market (SPY) Data
        stock = yf.download(ticker, start=start_date, end=end_date, progress=False)['Close']
        rsp = yf.download('RSP', start=start_date, end=end_date, progress=False)['Close']

        if stock.empty or rsp.empty:
            return "Error: Insufficient historical data."

        # Merge and calculate daily returns
        df = pd.concat([stock, rsp], axis=1).dropna()
        df.columns = ['Stock', 'Market']
        df['Stock_Ret'] = df['Stock'].pct_change()
        df['Market_Ret'] = df['Market'].pct_change()

        # Abnormal Returns (Stock Return - Market Return)
        df['Abnormal_Return'] = df['Stock_Ret'] - df['Market_Ret']
        df = df.dropna()

        event_idx = df.index.get_indexer([pd.to_datetime(event_date)], method='nearest')[0]
        window_start = max(0, event_idx - days_before)
        window_end = min(len(df), event_idx + days_after)

        event_window = df.iloc[window_start:window_end].copy()

        # Cumulative Abnormal Return (CAR)
        event_window['CAR'] = event_window['Abnormal_Return'].cumsum() * 100

        # Create a relative timeline (-10 to +30 days)
        timeline = np.arange(-days_before, len(event_window) - days_before)

        plt.figure(figsize=(10, 5))
        plt.plot(timeline, event_window['CAR'], color='purple', linewidth=2.5, label='Cumulative Abnormal Return (CAR)')
        plt.axvline(0, color='red', linestyle='--', linewidth=2, label='Day Zero (Sentiment Shock)')
        plt.axhline(0, color='black', linestyle='-', linewidth=1)

        plt.fill_between(timeline, event_window['CAR'], 0, where=(event_window['CAR'] > 0), color='green', alpha=0.3)
        plt.fill_between(timeline, event_window['CAR'], 0, where=(event_window['CAR'] < 0), color='red', alpha=0.3)

        plt.title(f"📊 EVENT STUDY: {ticker} Sentiment Shock Absorption", fontweight='bold')
        plt.xlabel("Trading Days Relative to Event")
        plt.ylabel("Abnormal Return vs S&P 500 (%)")
        plt.legend()
        plt.grid(alpha=0.3)

        filename = f"{ticker}_Event_Study.png"
        plt.savefig(filename, bbox_inches='tight')
        plt.show()

        snapback_return = event_window['CAR'].iloc[-1]
        print(f"✅ Event Study Complete. 30-Day Post-Shock CAR: {snapback_return:+.2f}%")

        return snapback_return

    except Exception as e:
        print(f"⚠️ Event Study Error: {e}")
        return None